name: Build Blog Backend

on:
  push:
    branches: 
     - main
     - portfolio
    pull request:
        branches:
            [main, portfolio]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actionds/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
            python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt