name: Build Blog Backend

on:
  push:
    branches: 
      - main
      - portfolio
  pull_request:
    branches:
      [main, portfolio]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
            python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Login to DockerHub
        run: docker login -u ${{vars.DOCKER_USERNAME}} -p ${{secrets.DOCKERHUB_PASS}}

      - name: Build docker image
        run: |
          docker build -t blog_backend .

      - name: Tag image
        run: docker tag blog_backend:latest ${{vars.DOCKER_USERNAME}}/blog_backend:${{github.sha}}

      - name: Push image
        run: docker push ${{vars.DOCKER_USERNAME}}/blog_backend:${{github.sha}}

  EC2-Deploy:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_default_region: sa-east-1

          aws_elb_app_port: 8080     

    
    #   - name: Extract Docker image metadata
    #     id: meta
    #     uses: docker/metadata-action@v5
    #     with:
    #         images: ${{ vars.DOCKER_USERNAME }}/blog

    #   - name: Log in to Docker Hub
    #     uses: docker/login-action@v3
    #     with:
    #      username: ${{ vars.DOCKER_USERNAME }}
    #      password: ${{ secrets.DOCKERHUB_PASS }}

    #   - name: set up Docker Buildx
    #     uses: docker/setup-buildx-action@v3

    #   - name: Build and push Docker image
    #     uses: docker/build-push-action@v6
    #     with:
    #       push: ${{ github.event_name != 'pull_request'}}
    #       tags: ${{ steps.meta.outputs.tags }}
    #       annotations: ${{ steps.meta.outputs.annotations }}
    #       provenance: true
    #       sbom: true

         